services:

  nginx:
    restart: always
    networks:
      - internal_net
    ports:
      - "80:80"
      - "443:443"
    image: docker.io/overtone1000/nginx_certbot:alpine
    volumes:
      - nginx:/etc/nginx/sites-available/ #certbot will make changes that need to persist
      - static_content:/var/www/html/ #allow static content to persist
      - certbot:/etc/letsencrypt/ #certbot will make changes that need to persist
      - certbot_var:/var/lib/letsencrypt/ #certbot will make changes that need to persist  
      #- /etc/timezone:/etc/timezone:ro  #Set time zone to be the same as the host machine
      #- /etc/localtime:/etc/localtime:ro #Set local time to be the same as the host machine
    environment:
      CERTBOT_WEBHOOK_PRE: "https://health.overdesigned.org/ping/483c2762-92e7-433a-93b1-d0f7a841ba41/start" #webhook for certbot pre-renewal
      CERTBOT_WEBHOOK_POST: "https://health.overdesigned.org/ping/483c2762-92e7-433a-93b1-d0f7a841ba41" #webhook for certbot post-renewal
      HEALTHCHECK_URL: "https://health.overdesigned.org/ping/00242d37-a34f-47ff-9f19-2ca0b3d44b59" #webhook for certbot post-renewal
    logging:
      driver: json-file
      options:
        max-size: 1m

volumes:
  cron:
    name: nginx_trm_cron
  nginx:
    name: nginx_trm_nginxconfig
  static_content:
    name: nginx_trm_static_content
  certbot:
    name: nginx_trm_certbot
  certbot_var:
    name: nginx_trm_certbotvar

networks:
  internal_net:
    name: internal_net
    driver: bridge
    attachable: true
    dns_enabled: true